version: '3.3'
services:
    postgres:
        container_name: pong-tracker-postgres
        environment:
            - POSTGRES_PASSWORD=PatrickMahomes15$$
        volumes:
            - '~/postgres-data/:/var/lib/postgresql/data'
        logging:
            driver: none
        ports:
            - '5432:5432'
        image: postgres
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: root
            GUNICORN_ACCESS_LOGFILE: '/dev/null'
        logging:
            driver: none
        ports:
        - "5050:80"